# packages in environment at C:\Users\hansh\anaconda3\envs\DRRT_BP001:
#
# Name                    Version                   Build  Channel
asgiref                   3.7.2                    pypi_0    pypi
bzip2                     1.0.8                he774522_0  
ca-certificates           2023.08.22           haa95532_0  
certifi                   2023.7.22                pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        3.2.0                    pypi_0    pypi
cryptography              41.0.2                   pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
django                    4.2.3                    pypi_0    pypi
django-cors-headers       4.2.0                    pypi_0    pypi
django-environ            0.10.0                   pypi_0    pypi
django-templated-mail     1.1.1                    pypi_0    pypi
djangorestframework       3.14.0                   pypi_0    pypi
djangorestframework-simplejwt 5.2.2                    pypi_0    pypi
djoser                    2.2.0                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
libffi                    3.4.4                hd77b12b_0  
oauthlib                  3.2.2                    pypi_0    pypi
openssl                   1.1.1w               h2bbff1b_0  
pip                       23.3            py311haa95532_0  
pycparser                 2.21                     pypi_0    pypi
pyjwt                     2.8.0                    pypi_0    pypi
python                    3.11.0               h966fe2a_3  
python3-openid            3.2.0                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
setuptools                68.0.0          py311haa95532_0  
social-auth-app-django    5.2.0                    pypi_0    pypi
social-auth-core          4.4.2                    pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0  
sqlparse                  0.4.4                    pypi_0    pypi
tk                        8.6.12               h2bbff1b_0  
typing-extensions         4.7.1                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
urllib3                   2.0.4                    pypi_0    pypi
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
wheel                     0.41.2          py311haa95532_0  
xz                        5.4.2                h8cc25b3_0  
zlib                      1.2.13               h8cc25b3_0  
